export interface WmoInfo {
  code: number;
  label: string;
  description: string;
  iconName: string; // Lucide icon identifier key
  group: 'clear' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  bgGradientDay: string;
  bgGradientNight: string;
  cardColor: string;
}

export const WMO_CODES: Record<number, WmoInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Completely clear skies with bright visibility',
    iconName: 'Sun',
    group: 'clear',
    bgGradientDay: 'from-amber-400 via-sky-400 to-blue-500',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-slate-900',
    cardColor: 'bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-500/20',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with scattered faint clouds',
    iconName: 'SunDim',
    group: 'clear',
    bgGradientDay: 'from-sky-400 via-blue-400 to-indigo-500',
    bgGradientNight: 'from-slate-900 via-indigo-900 to-slate-950',
    cardColor: 'bg-sky-500/10 text-sky-700 dark:text-sky-300 border-sky-500/20',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Intermittent sunshine filtered through light clouds',
    iconName: 'CloudSun',
    group: 'cloudy',
    bgGradientDay: 'from-blue-400 via-sky-300 to-slate-400',
    bgGradientNight: 'from-slate-900 via-slate-800 to-zinc-900',
    cardColor: 'bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/20',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Thick uniform cloud cover across the sky',
    iconName: 'Cloud',
    group: 'cloudy',
    bgGradientDay: 'from-slate-400 via-gray-400 to-slate-500',
    bgGradientNight: 'from-slate-950 via-zinc-900 to-slate-900',
    cardColor: 'bg-slate-500/10 text-slate-700 dark:text-slate-300 border-slate-500/20',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Dense low fog reducing visibility',
    iconName: 'CloudFog',
    group: 'fog',
    bgGradientDay: 'from-slate-300 via-zinc-400 to-slate-500',
    bgGradientNight: 'from-zinc-900 via-slate-900 to-zinc-950',
    cardColor: 'bg-zinc-500/10 text-zinc-700 dark:text-zinc-300 border-zinc-500/20',
  },
  48: {
    code: 48,
    label: 'Rime Fog',
    description: 'Freezing rime fog creating icy coats on objects',
    iconName: 'CloudFog',
    group: 'fog',
    bgGradientDay: 'from-cyan-200 via-slate-300 to-zinc-400',
    bgGradientNight: 'from-slate-900 via-cyan-950 to-slate-950',
    cardColor: 'bg-cyan-500/10 text-cyan-700 dark:text-cyan-300 border-cyan-500/20',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Gentle mist-like rain drops falling intermittently',
    iconName: 'CloudDrizzle',
    group: 'drizzle',
    bgGradientDay: 'from-sky-300 via-slate-400 to-blue-500',
    bgGradientNight: 'from-slate-900 via-slate-800 to-blue-950',
    cardColor: 'bg-sky-500/10 text-sky-700 dark:text-sky-300 border-sky-500/20',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Continuous fine drizzle with misty air',
    iconName: 'CloudDrizzle',
    group: 'drizzle',
    bgGradientDay: 'from-blue-400 via-slate-500 to-indigo-600',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-950',
    cardColor: 'bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/20',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy constant drizzle creating wet surfaces quickly',
    iconName: 'CloudDrizzle',
    group: 'drizzle',
    bgGradientDay: 'from-blue-500 via-slate-600 to-indigo-700',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-slate-900',
    cardColor: 'bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/20',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Supercooled drizzle freezing on contact with ground',
    iconName: 'CloudHail',
    group: 'drizzle',
    bgGradientDay: 'from-cyan-400 via-slate-500 to-blue-600',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-slate-900',
    cardColor: 'bg-cyan-500/10 text-cyan-700 dark:text-cyan-300 border-cyan-500/20',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy freezing drizzle causing slick icy roads',
    iconName: 'CloudHail',
    group: 'drizzle',
    bgGradientDay: 'from-teal-500 via-slate-600 to-blue-700',
    bgGradientNight: 'from-slate-950 via-teal-950 to-slate-900',
    cardColor: 'bg-teal-500/10 text-teal-700 dark:text-teal-300 border-teal-500/20',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light rain showers requiring an umbrella',
    iconName: 'CloudRain',
    group: 'rain',
    bgGradientDay: 'from-sky-400 via-blue-500 to-indigo-600',
    bgGradientNight: 'from-slate-900 via-blue-950 to-indigo-950',
    cardColor: 'bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/20',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady rainfall with puddles forming',
    iconName: 'CloudRain',
    group: 'rain',
    bgGradientDay: 'from-blue-500 via-indigo-600 to-slate-700',
    bgGradientNight: 'from-slate-950 via-blue-950 to-zinc-900',
    cardColor: 'bg-blue-600/10 text-blue-800 dark:text-blue-200 border-blue-600/20',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Pouring torrential rain with low visibility',
    iconName: 'CloudRainWind',
    group: 'rain',
    bgGradientDay: 'from-indigo-600 via-blue-700 to-slate-800',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-zinc-950',
    cardColor: 'bg-indigo-600/10 text-indigo-800 dark:text-indigo-200 border-indigo-600/20',
  },
  66: {
    code: 66,
    label: 'Freezing Rain',
    description: 'Light freezing rain producing a glaze of ice',
    iconName: 'CloudHail',
    group: 'rain',
    bgGradientDay: 'from-cyan-500 via-blue-600 to-slate-700',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-slate-900',
    cardColor: 'bg-cyan-500/10 text-cyan-700 dark:text-cyan-300 border-cyan-500/20',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain with treacherous ice accumulations',
    iconName: 'CloudHail',
    group: 'rain',
    bgGradientDay: 'from-teal-600 via-blue-700 to-slate-800',
    bgGradientNight: 'from-slate-950 via-teal-950 to-zinc-950',
    cardColor: 'bg-teal-600/10 text-teal-800 dark:text-teal-200 border-teal-600/20',
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Gentle snowflakes falling steadily',
    iconName: 'CloudSnow',
    group: 'snow',
    bgGradientDay: 'from-sky-200 via-indigo-300 to-slate-400',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-slate-950',
    cardColor: 'bg-sky-400/10 text-sky-800 dark:text-sky-200 border-sky-400/20',
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Consistent snow accumulation on ground surfaces',
    iconName: 'CloudSnow',
    group: 'snow',
    bgGradientDay: 'from-sky-300 via-blue-300 to-slate-500',
    bgGradientNight: 'from-slate-950 via-slate-900 to-indigo-950',
    cardColor: 'bg-blue-400/10 text-blue-800 dark:text-blue-200 border-blue-400/20',
  },
  75: {
    code: 75,
    label: 'Heavy Snow',
    description: 'Blinding snowstorm with rapid depth accumulation',
    iconName: 'Snowflake',
    group: 'snow',
    bgGradientDay: 'from-blue-200 via-indigo-400 to-slate-600',
    bgGradientNight: 'from-slate-950 via-zinc-900 to-slate-900',
    cardColor: 'bg-indigo-400/10 text-indigo-800 dark:text-indigo-200 border-indigo-400/20',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Tiny white opaque ice grains falling',
    iconName: 'Snowflake',
    group: 'snow',
    bgGradientDay: 'from-slate-300 via-sky-300 to-indigo-400',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-zinc-900',
    cardColor: 'bg-slate-400/10 text-slate-800 dark:text-slate-200 border-slate-400/20',
  },
  80: {
    code: 80,
    label: 'Light Rain Showers',
    description: 'Brief passing showers with sudden sunshine bursts',
    iconName: 'CloudSunRain',
    group: 'rain',
    bgGradientDay: 'from-sky-400 via-blue-400 to-slate-500',
    bgGradientNight: 'from-slate-900 via-blue-900 to-slate-950',
    cardColor: 'bg-sky-500/10 text-sky-700 dark:text-sky-300 border-sky-500/20',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Heavy bursts of rain showers alternating with calm',
    iconName: 'CloudRain',
    group: 'rain',
    bgGradientDay: 'from-blue-400 via-sky-500 to-indigo-600',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-slate-900',
    cardColor: 'bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/20',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Torrential downpours with strong sudden winds',
    iconName: 'CloudRainWind',
    group: 'rain',
    bgGradientDay: 'from-indigo-700 via-blue-800 to-slate-900',
    bgGradientNight: 'from-zinc-950 via-indigo-950 to-slate-950',
    cardColor: 'bg-indigo-700/10 text-indigo-800 dark:text-indigo-200 border-indigo-700/20',
  },
  85: {
    code: 85,
    label: 'Light Snow Showers',
    description: 'Scattered brief snow flurries',
    iconName: 'CloudSnow',
    group: 'snow',
    bgGradientDay: 'from-sky-300 via-slate-300 to-blue-400',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-950',
    cardColor: 'bg-sky-400/10 text-sky-700 dark:text-sky-300 border-sky-400/20',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls with sudden visibility drop',
    iconName: 'Snowflake',
    group: 'snow',
    bgGradientDay: 'from-blue-300 via-indigo-400 to-slate-600',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-zinc-950',
    cardColor: 'bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/20',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Lightning strikes with thunder and heavy rain',
    iconName: 'CloudLightning',
    group: 'thunderstorm',
    bgGradientDay: 'from-purple-600 via-indigo-700 to-slate-900',
    bgGradientNight: 'from-slate-950 via-purple-950 to-zinc-950',
    cardColor: 'bg-purple-500/10 text-purple-700 dark:text-purple-300 border-purple-500/20',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Light Hail',
    description: 'Thunderstorm accompanied by small ice hail stones',
    iconName: 'CloudLightning',
    group: 'thunderstorm',
    bgGradientDay: 'from-purple-700 via-slate-800 to-blue-900',
    bgGradientNight: 'from-zinc-950 via-purple-950 to-slate-950',
    cardColor: 'bg-purple-600/10 text-purple-800 dark:text-purple-200 border-purple-600/20',
  },
  99: {
    code: 99,
    label: 'Severe Hail Thunderstorm',
    description: 'Dangerous thunderstorm with large damaging hail',
    iconName: 'CloudLightning',
    group: 'thunderstorm',
    bgGradientDay: 'from-purple-900 via-slate-900 to-zinc-950',
    bgGradientNight: 'from-black via-purple-950 to-zinc-950',
    cardColor: 'bg-purple-700/10 text-purple-900 dark:text-purple-100 border-purple-700/20',
  },
};

export function getWmoInfo(code: number): WmoInfo {
  return (
    WMO_CODES[code] || {
      code,
      label: 'Unknown Condition',
      description: 'Variable weather conditions',
      iconName: 'Cloud',
      group: 'cloudy',
      bgGradientDay: 'from-slate-400 via-gray-400 to-slate-500',
      bgGradientNight: 'from-slate-950 via-zinc-900 to-slate-900',
      cardColor: 'bg-slate-500/10 text-slate-700 dark:text-slate-300 border-slate-500/20',
    }
  );
}
